در صورت وجود همبستگی زیاد بین دو فیچر بیشترین تاثیر منفی بر کدام یک از مدل های کلاسبک است


1-Linear models (e.g., linear regression or logistic regression), multicolinearity can yield solutions that are wildly varying and possibly numerically unstable.<br>
2-Random forests can be good at detecting interactions between different features, but highly correlated features can mask these interactions.

-----------------------------------------------------------------------------------------------------

نوشته و برای پیدا کردن آن ها از کدام فانکشن در کد استفاده میشود percision و recallفرمول 

Recall = TruePositives / (TruePositives + FalseNegatives) <br>
recall_score()<br>
Precision = TruePositives / (TruePositives + FalsePositives) <br>
precision_score()

-----------------------------------------------------------------------------------------------------

چیست و کدام یک معادل ریکال است roc curveدو پارامتر مهم در  

True Positive Rate (TPR) is a synonym for recall and False Positive Rate (FPR)



-----------------------------------------------------------------------------------------------------

 چیستaucمنظور از  

auc : area under the curve <br>
AUC provides an aggregate measure of performance across all possible classification thresholds. One way of interpreting AUC is as the probability that the model ranks a random positive example more highly than a random negative example

-----------------------------------------------------------------------------------------------------

را نام ببرید و به طور کلی کرنل در این مدل یعنی انجام چه کاری؟svm kernels

Polynomial kernel<br>
RBF kernel<br>
linrear Kernel<br>
When using SVMs you can apply an almost miraculous mathematical
technique called the kernel trick. The kernel trick makes it
possible to get the same result as if you had added many polynomial features, even
with very high-degree polynomials, without actually having to add them. So there is
no combinatorial explosion of the number of features because you don’t actually add
any features.


-----------------------------------------------------------------------------------------------------

را می خواهیم پیاده سازی کنیم همانطور که میبیتید نسبت دیتاها بسیار متفاوت است چه راه حلی را پیشتهاد میکنید  svcدر دیتاستی ۱۰۰۰ داده با لیبل ۱ و ۲۰ داده با لیبل ۲ وجود دارد میخواهیم بر روی این دیتا مدل 

 Weighted SVM: the simplest and most common extension to SVM for imbalanced classification is to weight the C value in proportion to the importance of each class.<br>
 C_i = weight_i * C <br>
 Small Weight: Smaller C value, larger penalty for misclassified examples.<br>
Larger Weight: Larger C value, smaller penalty for misclassified examples.<br>
model = SVC(gamma='scale', class_weight='balanced')

-----------------------------------------------------------------------------------------------------

زیر برقرار است عدد ۲ و عدد ۳ چه مفهومی را می رساند  confusion matrix بر روی داده های پیش بینی شده توسط یک مدل و لیبل های واقعی آن 

In [ ]:
[[10  2 0]
 [ 0  8  3]
 [ 0  0 11]]

this confusion matrix is for a data set with 3 labels and 2 and 3 are the false negetive and 10, 8 and 11 are the true positive 

-----------------------------------------------------------------------------------------------------

کنیم چه روش هایی را استفاده میکنید model-base   الگوریتم است برای اینکه این الگوریتم را کمی شبیه الگوریتم هایinstance-base یک knn الگوریتم

1- We can integrated KNN and constrained logistic regression (KNNLog) approach for sparsef parametric estimation, which forces the irrelevant features to zero.<br>
2- There are also algorithm used to compute the nearest neighbors:<br>
‘ball_tree’ will use BallTree<br>
‘kd_tree’ will use KDTree<br>
‘brute’ will use a brute-force search

-----------------------------------------------------------------------------------------------------

را امتحان کنید svmروی دیتای زیر پارامترهای الگوریتم مناسب   

In [7]:
import pandas as pd
import numpy as np

In [8]:
from sklearn.datasets import load_wine
wine = load_wine(as_frame=True)

In [9]:
df=pd.DataFrame(data=np.c_[wine['data'],wine['target']],columns=wine['feature_names']+['target'])
df

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  target  
0                            3.92   1065.0     0.0  
1                            3.40   1050.0     0.0  
2                            3.17   1185.0     0.0  
3                            3.45   1480.0     0.0  
4                            2.93    735.0     0.0  
..                            ...      ...     ...  
173                          1.74    740.0     2.0  
174                          1.56    750.0     2.0  
175                          1.56    835.0     2.0  
176                          1.62    840.0     2.0  
177                          1.60    560.0     2.0  

[178 rows x 14 columns]

In [10]:
from sklearn.model_selection import train_test_split

In [12]:
X = df.drop('target', axis = 1).values
y = df['target'].values

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [25]:
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.metrics import accuracy_score

In [26]:
svc_model = make_pipeline(StandardScaler(), SVC())
svc_model.fit(X_train, y_train)
y_pred = svc_model.predict(X_test)
svc_model_acc = accuracy_score(y_test,y_pred)

In [27]:
svc_model_acc

0.9814814814814815

## linux


چند دیستربیوشن مهم لینوکس دز دنیای امروز را نام ببرید و منظور از کرنل چیست


There are three main “families” of Linux distributions: Debian, Red Hat, and SUSE. Most other Linux distributions use one of these three distributions as their foundation.<br>
Kernel: The Linux kernel is the main component of a Linux operating system (OS) and is the core interface between a computer’s hardware and its processes. It communicates between the 2, managing resources as efficiently as possible.
The kernel is so named because—like a seed inside a hard shell—it exists within the OS and controls all the major functions of the hardware, whether it’s a phone, laptop, server, or any other kind of computer.