<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=6 color=#F32500>
        <div  align=center>
            تمرین هفته سوم بوت کمپ یادگیری ماشین-
            مپصا
        </div>
        <br/>
    </font>
</div>


<div style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
		<div align=center>
			<font face="IranNastaliq" size=5>    
                  چون عهده نمی‌شود کسی فردا را
                <br><br>
                 حالی خوش دار این دل پر سودا را
                <br><br>
                می نوش به ماهتاب ای ماه که ماه
                <br><br>
                بسیار بتابد و نیابد ما را        			   	
                <p></p>
			</font>
        </div>
    </font>
</div>


In [21]:
import numpy as np
import pandas as pd

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
		<font color=red size=5>
            سوال اول:‌
            </font>
        <font>
            مجموعه داده های زیر را در نظر بگیرید
        </font>
        <br/>
    </font>
</div>

In [22]:
numbers = np.array([ 4.5 , 7.8 ,  6.5,  0.5,  8. ,  6.5, 19. , 13.5,  2.5, 17. , 19. ,
       19.5, 13. ,  12.21 ,  6.3 ,  0.5,  9.5, 13.5, 16. ,  2.5, 10.5,  8. ,
       10. , 15.5,  7.5,  0. ,  1. , 10.5,  2. , 11. ,  3. , 14. ,  3.5,
       18.5, 13. ,  1. , 14.5, 15. ,  1.52 , 15.5,  1.5,  2.8 ,  3.5,  6.5,
        12.5, 14.5, 11.5,  8. ,  10.2 ,  5.5,  0.5, 23. ,  5. ,  0.5, 17.5,
       17.5, 17.5, 15. ,  4.5, 17. , 18. , 10. ,  8.5, 14. , 18.5, 19.5,
       16.3 ,  8.5,  0. ,  9.5,  6. ,  2. ,  5. ,  9.5,  4. ,  4. ,  1. ,
        8. , 18.5, 18. , 15.5,  4.5,  1.5, 20. ,  0.5, 19. ,  4. ,  9.5,
       12.8  ])
numbers

array([ 4.5 ,  7.8 ,  6.5 ,  0.5 ,  8.  ,  6.5 , 19.  , 13.5 ,  2.5 ,
       17.  , 19.  , 19.5 , 13.  , 12.21,  6.3 ,  0.5 ,  9.5 , 13.5 ,
       16.  ,  2.5 , 10.5 ,  8.  , 10.  , 15.5 ,  7.5 ,  0.  ,  1.  ,
       10.5 ,  2.  , 11.  ,  3.  , 14.  ,  3.5 , 18.5 , 13.  ,  1.  ,
       14.5 , 15.  ,  1.52, 15.5 ,  1.5 ,  2.8 ,  3.5 ,  6.5 , 12.5 ,
       14.5 , 11.5 ,  8.  , 10.2 ,  5.5 ,  0.5 , 23.  ,  5.  ,  0.5 ,
       17.5 , 17.5 , 17.5 , 15.  ,  4.5 , 17.  , 18.  , 10.  ,  8.5 ,
       14.  , 18.5 , 19.5 , 16.3 ,  8.5 ,  0.  ,  9.5 ,  6.  ,  2.  ,
        5.  ,  9.5 ,  4.  ,  4.  ,  1.  ,  8.  , 18.5 , 18.  , 15.5 ,
        4.5 ,  1.5 , 20.  ,  0.5 , 19.  ,  4.  ,  9.5 , 12.8 ])

<div id="bayes" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
		<p></p>
        برای این مجموعه داده ها قصد داریم با دو فرمول زیر مقادیر آنها را تغییر دهیم:
<br>
۱. اگر عددی کمتر از هشت و نیم است با فرمول زیر آن عدد تغییر کند:
<br>
$$ y = 10 + \frac{x}{10} $$
<br>
۲. اگر عددیبیشتر یا مساوی هشت و نیم است با فرمول زیر آن عدد تغییر کند :
<br>
$$ y =  -0.0051x^{2} + 0.8586x + 3.4332 $$
<br>
توجه کنید که حتی بعد از تغییر باید بیشینه عدد نهایتا بیشینه عدد موجود در داده فعلی باشد. 25 درصد داده های بزرگتر را در آرایه زیر بریزید
</div>

In [23]:
np.max(numbers)

23.0

In [24]:
mask1=np.zeros(len(numbers))
mask1[numbers<8.5] = 1
mask2=np.zeros(len(numbers))
mask2[numbers>=8.5] = 1

In [25]:
numbers_changed = mask1 * (numbers/10 + 10) + mask2 * (-0.0051 * numbers ** 2 + 0.8586 * numbers + 3.4332)
numbers_changed

array([10.45      , 10.78      , 10.65      , 10.05      , 10.8       ,
       10.65      , 17.9055    , 14.094825  , 10.25      , 16.5555    ,
       17.9055    , 18.236625  , 13.7331    , 13.15637709, 10.63      ,
       10.05      , 11.129625  , 14.094825  , 15.8652    , 10.25      ,
       11.886225  , 10.8       , 11.5092    , 15.516225  , 10.75      ,
       10.        , 10.1       , 11.886225  , 10.2       , 12.2607    ,
       10.3       , 14.454     , 10.35      , 17.571825  , 13.7331    ,
       10.1       , 14.810625  , 15.1647    , 10.152     , 15.516225  ,
       10.15      , 10.28      , 10.35      , 10.65      , 13.368825  ,
       14.810625  , 12.632625  , 10.8       , 11.660316  , 10.55      ,
       10.05      , 20.4831    , 10.5       , 10.05      , 16.896825  ,
       16.896825  , 16.896825  , 15.1647    , 10.45      , 16.5555    ,
       17.2356    , 11.5092    , 10.362825  , 14.454     , 17.571825  ,
       18.236625  , 16.073361  , 10.362825  , 10.        , 11.12

In [26]:
np.max(numbers_changed)

20.4831

In [27]:
top_new_twenty_five = numbers_changed[numbers_changed>=np.quantile(numbers_changed,0.75)]
top_new_twenty_five

array([17.9055  , 16.5555  , 17.9055  , 18.236625, 15.8652  , 15.516225,
       17.571825, 15.1647  , 15.516225, 20.4831  , 16.896825, 16.896825,
       16.896825, 15.1647  , 16.5555  , 17.2356  , 17.571825, 18.236625,
       16.073361, 17.571825, 17.2356  , 15.516225, 18.5652  , 17.9055  ])

<div id="bayes" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
		<p></p>
 25 درصد داده های کوچکتر آرایه اول را در آرایه زیر بریزید
</div>

In [28]:
down_old_twenty_five = numbers[numbers<=np.quantile(numbers,0.25)]
down_old_twenty_five

array([0.5 , 2.5 , 0.5 , 2.5 , 0.  , 1.  , 2.  , 3.  , 3.5 , 1.  , 1.52,
       1.5 , 2.8 , 3.5 , 0.5 , 0.5 , 0.  , 2.  , 4.  , 4.  , 1.  , 1.5 ,
       0.5 , 4.  ])

<div id="bayes" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
      <p></p>
        داده های متناظر دو آرایه به دست آمده را از یکدیگر کسر کنید و در یک آرایه سه بعدی که اندازه ابعاد سوم و دوم آن یک میباشد بریزید
</div>

In [29]:
new_array_three_dimension = np.ones((len(down_old_twenty_five),1,1))
new_array_three_dimension[:,0,0] = top_new_twenty_five - down_old_twenty_five
new_array_three_dimension

array([[[17.4055  ]],

       [[14.0555  ]],

       [[17.4055  ]],

       [[15.736625]],

       [[15.8652  ]],

       [[14.516225]],

       [[15.571825]],

       [[12.1647  ]],

       [[12.016225]],

       [[19.4831  ]],

       [[15.376825]],

       [[15.396825]],

       [[14.096825]],

       [[11.6647  ]],

       [[16.0555  ]],

       [[16.7356  ]],

       [[17.571825]],

       [[16.236625]],

       [[12.073361]],

       [[13.571825]],

       [[16.2356  ]],

       [[14.016225]],

       [[18.0652  ]],

       [[13.9055  ]]])

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
		<font color=red size=5>
            سوال دوم:‌
        </font>
در این تمرین قصد داریم به تحلیل داده های فیلم های برتر سینمای جهان به معیار imdb بپردازیم. ابتدا دادههای مربوط به فیلم را از فایل csv فراخوانی میکنیم
        <br/>
    </font>
</div>

In [30]:
movies = pd.read_csv("imdb_movie_rank.csv")
movies

star_rating                                            title  \
0            9.3                         The Shawshank Redemption   
1            9.2                                    The Godfather   
2            9.1                           The Godfather: Part II   
3            9.0                                  The Dark Knight   
4            8.9                                     Pulp Fiction   
..           ...                                              ...   
974          7.4                                          Tootsie   
975          7.4                      Back to the Future Part III   
976          7.4  Master and Commander: The Far Side of the World   
977          7.4                                      Poltergeist   
978          7.4                                      Wall Street   

    content_rating      genre  duration  \
0                R      Crime       142   
1                R      Crime       175   
2                R      Crime       200   
3            PG-13     Action       152   
4                R      Crime       154   
..             ...        ...       ...   
974             PG     Comedy       116   
975             PG  Adventure       118   
976          PG-13     Action       138   
977             PG     Horror       114   
978              R      Crime       126   

                                           actors_list  
0    [u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt...  
1      [u'Marlon Brando', u'Al Pacino', u'James Caan']  
2    [u'Al Pacino', u'Robert De Niro', u'Robert Duv...  
3    [u'Christian Bale', u'Heath Ledger', u'Aaron E...  
4    [u'John Travolta', u'Uma Thurman', u'Samuel L....  
..                                                 ...  
974  [u'Dustin Hoffman', u'Jessica Lange', u'Teri G...  
975  [u'Michael J. Fox', u'Christopher Lloyd', u'Ma...  
976  [u'Russell Crowe', u'Paul Bettany', u'Billy Bo...  
977  [u'JoBeth Williams', u"Heather O'Rourke", u'Cr...  
978  [u'Charlie Sheen', u'Michael Douglas', u'Tamar...  

[979 rows x 6 columns]

In [31]:
movies.describe()

star_rating    duration
count   979.000000  979.000000
mean      7.889785  120.979571
std       0.336069   26.218010
min       7.400000   64.000000
25%       7.600000  102.000000
50%       7.800000  117.000000
75%       8.100000  134.000000
max       9.300000  242.000000


<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
        در این دیتاست اگر داده ای وجود دارد که مقدار nullدارد سطرش را حذف کنید. 
        <br/>
    </font>
</div>

In [32]:
movies.isnull().sum()

star_rating       0
title             0
content_rating    3
genre             0
duration          0
actors_list       0
dtype: int64

In [33]:
movies.dropna(axis=0,inplace=True)

In [34]:
movies.head(30)

star_rating                                              title  \
0           9.3                           The Shawshank Redemption   
1           9.2                                      The Godfather   
2           9.1                             The Godfather: Part II   
3           9.0                                    The Dark Knight   
4           8.9                                       Pulp Fiction   
5           8.9                                       12 Angry Men   
6           8.9                     The Good, the Bad and the Ugly   
7           8.9      The Lord of the Rings: The Return of the King   
8           8.9                                   Schindler's List   
9           8.9                                         Fight Club   
10          8.8  The Lord of the Rings: The Fellowship of the Ring   
11          8.8                                          Inception   
12          8.8     Star Wars: Episode V - The Empire Strikes Back   
13          8.8                                       Forrest Gump   
14          8.8              The Lord of the Rings: The Two Towers   
15          8.7                                       Interstellar   
16          8.7                    One Flew Over the Cuckoo's Nest   
17          8.7                                      Seven Samurai   
18          8.7                                         Goodfellas   
19          8.7                                          Star Wars   
20          8.7                                         The Matrix   
21          8.7                                        City of God   
22          8.7                              It's a Wonderful Life   
23          8.7                                 The Usual Suspects   
24          8.7                                              Se7en   
25          8.6                                  Life Is Beautiful   
26          8.6                       Once Upon a Time in the West   
27          8.6                           The Silence of the Lambs   
28          8.6                             Leon: The Professional   
29          8.6                                        City Lights   

   content_rating      genre  duration  \
0               R      Crime       142   
1               R      Crime       175   
2               R      Crime       200   
3           PG-13     Action       152   
4               R      Crime       154   
5       NOT RATED      Drama        96   
6       NOT RATED    Western       161   
7           PG-13  Adventure       201   
8               R  Biography       195   
9               R      Drama       139   
10          PG-13  Adventure       178   
11          PG-13     Action       148   
12             PG     Action       124   
13          PG-13      Drama       142   
14          PG-13  Adventure       179   
15          PG-13  Adventure       169   
16              R      Drama       133   
17        UNRATED      Drama       207   
18              R  Biography       146   
19             PG     Action       121   
20              R     Action       136   
21              R      Crime       130   
22       APPROVED      Drama       130   
23              R      Crime       106   
24              R      Drama       127   
25          PG-13     Comedy       116   
26          PG-13    Western       175   
27              R      Drama       118   
28              R      Crime       110   
29         PASSED     Comedy        87   

                                          actors_list  
0   [u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt...  
1     [u'Marlon Brando', u'Al Pacino', u'James Caan']  
2   [u'Al Pacino', u'Robert De Niro', u'Robert Duv...  
3   [u'Christian Bale', u'Heath Ledger', u'Aaron E...  
4   [u'John Travolta', u'Uma Thurman', u'Samuel L....  
5   [u'Henry Fonda', u'Lee J. Cobb', u'Martin Bals...  
6   [u'Clint Eastwood', u'Eli Wallach', u'Lee Van ...  
7   [u'Elijah Wood', u'Viggo Mortensen', u'Ian McK...  
8   [u'Liam Neeson', u'Ral

In [35]:
movies.isnull().sum()

star_rating       0
title             0
content_rating    0
genre             0
duration          0
actors_list       0
dtype: int64

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
        فیلم ها را براساس مدت زمان فیلم به صورت نزولی مرتب کنید و پنجاه تای اول را در فایل csv با نام long_time ذخیره کنید 
        <br/>
    </font>
</div>

In [36]:
movies.sort_values(by="duration",ascending=False).head(50).to_csv("long_time.csv",header=True,index=False)

In [37]:
sorted_movie = pd.read_csv("long_time.csv")
sorted_movie

star_rating                                              title  \
0           7.8                                             Hamlet   
1           8.2                                 Gone with the Wind   
2           8.4                        Once Upon a Time in America   
3           8.3                  Lagaan: Once Upon a Time in India   
4           7.9                               The Ten Commandments   
5           8.4                                 Lawrence of Arabia   
6           8.1                                            Ben-Hur   
7           8.7                                      Seven Samurai   
8           7.6                    It's a Mad, Mad, Mad, Mad World   
9           7.7                                          Malcolm X   
10          8.9      The Lord of the Rings: The Return of the King   
11          9.1                             The Godfather: Part II   
12          8.0                                     Doctor Zhivago   
13          8.0                                          Spartacus   
14          8.9                                   Schindler's List   
15          7.7                                            Titanic   
16          7.9                                    The Right Stuff   
17          8.1                                             Gandhi   
18          7.7                                         Grindhouse   
19          8.5                                     The Green Mile   
20          8.4                                             Swades   
21          8.0                                                JFK   
22          8.0                                           Magnolia   
23          8.2                                Fanny and Alexander   
24          7.7                                         Short Cuts   
25          8.3                              Judgment at Nuremberg   
26          8.1                                       Barry Lyndon   
27          8.3                                     Dil Chahta Hai   
28          8.2                                    The Deer Hunter   
29          8.0                                 Dances with Wolves   
30          8.4                        Dilwale Dulhania Le Jayenge   
31          8.0                                Fiddler on the Roof   
32          8.2                            The Wolf of Wall Street   
33          8.8              The Lord of the Rings: The Two Towers   
34          7.9                          Blue Is the Warmest Color   
35          8.8  The Lord of the Rings: The Fellowship of the Ring   
36          7.8                                    The Longest Day   
37          8.2                                             Casino   
38          8.0                                           Dogville   
39          8.4                                         Braveheart   
40          9.2                                      The Godfather   
41          7.4                                   A Bridge Too Far   
42          8.6                       Once Upon a Time in the West   
43          8.0                                 The Sound of Music   
44          8.1                                      La Dolce Vita   
45          8.2                        The Best Years of Our Lives   
46          8.0                                             Patton   
47          8.3                                   The Great Escape   
48          7.5                                        Cloud Atlas   
49          7.5                                        The Aviator   

   content_rating      genre  duration  \
0           PG-13      Drama       242   
1               G      Drama       238   
2               R      Crime       229   
3              PG  Adventure       224   
4        APPROVED  Adventure       220   
5              PG  Adventure       216   
6               G  Adventure       212   
7         UNRATED      Drama       207   
8        APPROVED     Action       205   
9           P

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
         تابعی بنویسید که نام بازیگر را به عنوان آرگومان بگیرد و تعداد فیلم های برتر از این لیست را که بازی کرده محاسبه کند.
        <br/>
    </font>
</div>

In [ ]:
movies

In [54]:
def movie_count_by_actor(name:str) -> int:
    count_list = movies["actors_list"].apply(lambda x : True if "Marlon Brando".lower().strip() in x.lower().strip() else False)
    count = np.cumsum(count_list)
    return np.max(count)

In [55]:
movie_count_by_actor("christian bale")

4

In [ ]:
#TODO

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
       ستونی به این داده ها اضافه کنید که در صورت اینکه یک فیلم مدت نمایش آن 150 دقیقه و یا بیشتر بود مقدار صفر و در غیر اینصورت 1 در هر سطر این ستون قرار گیرد. دیتافریم حاصل را در یک فایل csv ذخیره کنید.
        <br/>
    </font>
</div>

In [41]:
#TODO

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
        عنوان ستونها را به نحوی تغییر دهید که در ستون های دارای _(آندرلاین) فاصله قرار گیرد. به عنوان مثال star_rating به star rating تبدیل می شود.
        <br/>
    </font>
</div>

In [42]:
#TODO

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
        داده ها را براساس ژانر گروه بندی و مرتب کنید و از هر ژانر صرفا سه تای برتر را نمایش دهید
        <br/>
    </font>
</div>

In [43]:
#TODO

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
		<font color=red size=5>
            سوال سوم:‌
        </font>
        تفاوت بین متد read_table و read_csv در ماژول pandas چیست؟
        <br/>
    </font>
</div>

In [44]:
#TODO

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
		<font color=red size=5>
            سوال چهارم:‌
        </font>
       توضیح دهید crosstab در پانداس چه میکند و عملکرد آنرا بر روی کد زیر توضیح دهید؟
        <br/>
    </font>
</div>

In [45]:
pd.crosstab(movies.genre, movies.content_rating)

content_rating  APPROVED   G  GP  NC-17  NOT RATED  PASSED  PG  PG-13    R  \
genre                                                                        
Action                 3   1   1      0          4       1  11     44   67   
Adventure              3   2   0      0          5       1  21     23   17   
Animation              3  20   0      0          3       0  25      5    5   
Biography              1   2   1      0          1       0   6     29   36   
Comedy                 9   2   1      1         16       3  23     23   73   
Crime                  6   0   0      1          7       1   6      4   87   
Drama                 12   3   0      4         24       1  25     55  143   
Family                 0   1   0      0          0       0   1      0    0   
Fantasy                0   0   0      0          0       0   0      0    1   
Film-Noir              1   0   0      0          1       0   0      0    0   
History                0   0   0      0          0       0   0      0    0   
Horror                 2   0   0      1          1       0   1      2   16   
Mystery                4   1   0      0          1       0   1      2    6   
Sci-Fi                 1   0   0      0          0       0   0      1    3   
Thriller               1   0   0      0          0       0   1      0    3   
Western                1   0   0      0          2       0   2      1    3   

content_rating  TV-MA  UNRATED  X  
genre                              
Action              0        3  0  
Adventure           0        2  0  
Animation           0        1  0  
Biography           0        0  0  
Comedy              0        4  1  
Crime               0       11  1  
Drama               1        9  1  
Family              0        0  0  
Fantasy             0        0  0  
Film-Noir           0        1  0  
History             0        1  0  
Horror              0        5  1  
Mystery             0        1  0  
Sci-Fi              0        0  0  
Thriller            0        0  0  
Western             0        0  0

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
		<font color=red size=5>
            سوال پنچم:‌
        </font>
         توضیح دهید متد corr در پانداس چه میکند و عملکرد آنرا بر روی کد زیر توضیح دهید؟ 
        <br/>
    </font>
</div>

In [46]:
movies.corr()

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_548\3313059620.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  movies.corr()


star_rating  duration
star_rating      1.00000   0.22941
duration         0.22941   1.00000

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
		<font color=red size=5>
            سوال سوم:‌
        </font>
        با استفاده از متد value_counts تعداد فیلمها در هر ریت محتوا را به دست آورید.
        <br/>
    </font>
</div>

In [47]:
#TODO

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
		<font color=red size=5>
            سوال ششم:‌
        </font>
        با استفاده از متد sample هفتاد و پنج درصد سطرها را در یک متغیر به نام sample_1 بریزید. درنهایت با استفاده از متد drop از دیتافریم اصلی این سطرها را حذف و دیتافریم جدید را در sample_2 بریزید
        <br/>
    </font>
</div>

In [48]:
#TODO

<div dir = "rtl" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=4>
		<font color=red size=5>
            سوال هفتم:‌
        </font>
         متد pivot_table چه عملکردی دارد؟
        <br/>
    </font>
</div>

In [49]:
#TODO