<div dir = "rtl" style="direction:rtl;line-height:300%;">
    <font face="XB Zar" size=6 color=#F32500>
        <div  align=center>
            تمرین هفته دهم بوت کمپ یادگیری ماشین-
            مپصا
        </div>
        <br/>
    </font>
</div>

In [316]:
# import all packages and libraries here.

import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import classification_report
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd

# 1- State with reasons whether the following sentences are true or false?

<ul style="font-size:25px">
    <li>
        SVMs are not suitable for large datasets.
    </li>
    <li>
       SVMs perform poorly in imbalanced datasets.
    </li>
     <li>
        SVMs perform poorly when there is just too much noise in the data.
    </li>
</ul>

##  SVMs are not suitable for large datasets----->True                                  
normal SVM is not suitable for classification of large data sets, because the training complexity of SVM is very high

## SVMs perform poorly in imbalanced datasets.------->True                                     
SVMs are effective models for binary classification tasks, although by default, they are not effective at imbalanced classification

## SVMs perform poorly when there is just too much noise in the data----->True                  
SVM will not perform well with data with more noise because of the weakness of soft margin optimization issue. The unique hyperplane grabbed in the SVM process using the imbalanced data will be fully skewed towards a minority class.

In [317]:
# TODO

<div id="bayes" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=6>
		 ۲- دیتاست lsvt-voice-rehabilitation را از لینک زیر دانلود کنید و به سوالات زیر حواب دهید. در این تمرین مجاز به استفاده از کتابخانه scikit-learn می باشید.
		</br>
</div>
		https://archive.ics.uci.edu/ml/datasets/LSVT+Voice+Rehabilitation

In [343]:
df=pd.read_excel('LSVT_voice_rehabilitation.xlsx')
target=pd.read_excel('LSVT_voice_rehabilitation.xlsx',sheet_name ='Binary response')
df.head()

Jitter->F0_abs_dif  Jitter->F0_dif_percent  \
0            0.088112                0.041697   
1            0.161798                0.057364   
2            0.554508                0.642913   
3            0.031089                0.027108   
4            0.076177                0.039071   

   Jitter->F0_PQ5_classical_Schoentgen  Jitter->F0_PQ5_classical_Baken  \
0                             0.000480                   -3.723304e-06   
1                             0.000677                    5.466365e-06   
2                             0.007576                   -7.443871e-07   
3                             0.000314                   -2.214722e-07   
4                             0.000302                    2.732106e-05   

   Jitter->F0_PQ5_generalised_Schoentgen  Jitter->F0_abs0th_perturb  \
0                               0.000422                   2.458381   
1                               0.000206                   2.592066   
2                               0.006488                  12.691326   
3                               0.000216                   0.754288   
4                               0.001102                   1.270034   

   Jitter->F0_CV  Jitter->F0_TKEO_mean  Jitter->F0_TKEO_std  \
0   6.332164e-07             47.021079          1366.430390   
1   7.228518e-07             93.557936          2582.922776   
2   6.946246e-04             52.988422           466.682635   
3   1.868647e-07             13.982754           417.217249   
4   4.918186e-05             56.373996          1608.317410   

   Jitter->F0_TKEO_prc5  ...  det_TKEO_std4_1_coef  det_TKEO_std4_2_coef  \
0             -7.103323  ...              2.527583              7.088978   
1            -23.284761  ...              2.841881              7.977363   
2            -45.308680  ...              1.806103              5.078616   
3             -1.207741  ...              1.999637              5.610448   
4             -3.491990  ...              2.453087              6.902199   

   det_TKEO_std4_3_coef  det_TKEO_std4_4_coef  det_TKEO_std4_5_coef  \
0             19.753255             54.335046            145.528630   
1             22.203504             60.993338            163.560972   
2             14.135923             38.641654            103.466808   
3             15.626164             42.943275            115.014975   
4             19.117609             52.715873            141.113865   

   det_TKEO_std4_6_coef  det_TKEO_std4_7_coef  det_TKEO_std4_8_coef  \
0            375.097397            921.296579           2137.079844   
1            421.010306           1036.092589           2404.072562   
2            264.654626            649.657090           1507.384591   
3            296.320795            728.284936           1689.586636   
4            363.511021            893.246151           2071.625622   

   det_TKEO_std4_9_coef  det_TKEO_std4_10_coef  
0           4697.131077            9931.208257  
1           5284.082128           11165.095662  
2           3315.804236            6974.600636  
3           3713.818933            7851.139360  
4           4554.204815            9623.566242  

[5 rows x 310 columns]

In [344]:
target.columns=['lable']
df=pd.concat([df,target],axis=1)

In [345]:
df.head()

Jitter->F0_abs_dif  Jitter->F0_dif_percent  \
0            0.088112                0.041697   
1            0.161798                0.057364   
2            0.554508                0.642913   
3            0.031089                0.027108   
4            0.076177                0.039071   

   Jitter->F0_PQ5_classical_Schoentgen  Jitter->F0_PQ5_classical_Baken  \
0                             0.000480                   -3.723304e-06   
1                             0.000677                    5.466365e-06   
2                             0.007576                   -7.443871e-07   
3                             0.000314                   -2.214722e-07   
4                             0.000302                    2.732106e-05   

   Jitter->F0_PQ5_generalised_Schoentgen  Jitter->F0_abs0th_perturb  \
0                               0.000422                   2.458381   
1                               0.000206                   2.592066   
2                               0.006488                  12.691326   
3                               0.000216                   0.754288   
4                               0.001102                   1.270034   

   Jitter->F0_CV  Jitter->F0_TKEO_mean  Jitter->F0_TKEO_std  \
0   6.332164e-07             47.021079          1366.430390   
1   7.228518e-07             93.557936          2582.922776   
2   6.946246e-04             52.988422           466.682635   
3   1.868647e-07             13.982754           417.217249   
4   4.918186e-05             56.373996          1608.317410   

   Jitter->F0_TKEO_prc5  ...  det_TKEO_std4_2_coef  det_TKEO_std4_3_coef  \
0             -7.103323  ...              7.088978             19.753255   
1            -23.284761  ...              7.977363             22.203504   
2            -45.308680  ...              5.078616             14.135923   
3             -1.207741  ...              5.610448             15.626164   
4             -3.491990  ...              6.902199             19.117609   

   det_TKEO_std4_4_coef  det_TKEO_std4_5_coef  det_TKEO_std4_6_coef  \
0             54.335046            145.528630            375.097397   
1             60.993338            163.560972            421.010306   
2             38.641654            103.466808            264.654626   
3             42.943275            115.014975            296.320795   
4             52.715873            141.113865            363.511021   

   det_TKEO_std4_7_coef  det_TKEO_std4_8_coef  det_TKEO_std4_9_coef  \
0            921.296579           2137.079844           4697.131077   
1           1036.092589           2404.072562           5284.082128   
2            649.657090           1507.384591           3315.804236   
3            728.284936           1689.586636           3713.818933   
4            893.246151           2071.625622           4554.204815   

   det_TKEO_std4_10_coef  lable  
0            9931.208257      1  
1           11165.095662      2  
2            6974.600636      2  
3            7851.139360      1  
4            9623.566242      2  

[5 rows x 311 columns]

<div id="bayes" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=6>
		 الف- داده ها را به روشهای زیر دسته بندی کنید (حواستان باشد که داده ها را قبل از اعمال به مدل، نرمالایز کنید).
        <ul>
            <li>
            کرنل خطی
            </li>
            <li>
            کرنل چندجمله ای (پارامترهای r, d)
            </li>
            <li>
            کرنل rbf - پارامتر گاما
            </li>
            <li>
            سیگمویید - پارامتر r
            </li>           
         </ul>
</div

<div id="bayes" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=6>
		 ب- معیار دقت و f1 را برای هریک از دسته بندی های قسمت الف به دست آورید. (برای هر یک از پارامترهای گفته شده حداقل سه مقدار مختلف در نظر بگیرید)
		</br>
</div>

In [346]:
from sklearn.metrics import accuracy_score 

In [347]:
X = df.drop('lable', axis=1)
y = df['lable']

In [348]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [349]:
from sklearn.svm import SVC
linear = make_pipeline(preprocessing.StandardScaler(),SVC(kernel='linear'))
linear.fit(X_train, y_train)

y_pred1 = linear.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred1))
print(classification_report(y_test,y_pred1))
print(accuracy_score(y_test,y_pred1))

[[ 5  2]
 [ 1 18]]
              precision    recall  f1-score   support

           1       0.83      0.71      0.77         7
           2       0.90      0.95      0.92        19

    accuracy                           0.88        26
   macro avg       0.87      0.83      0.85        26
weighted avg       0.88      0.88      0.88        26

0.8846153846153846


In [361]:
poly = make_pipeline(preprocessing.StandardScaler(),SVC(kernel='poly'))
poly.fit(X_train, y_train)

y_pred2 = poly.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred2))
print(classification_report(y_test, y_pred2))
print(accuracy_score(y_test,y_pred2))

[[ 0  7]
 [ 0 19]]
              precision    recall  f1-score   support

           1       0.00      0.00      0.00         7
           2       0.73      1.00      0.84        19

    accuracy                           0.73        26
   macro avg       0.37      0.50      0.42        26
weighted avg       0.53      0.73      0.62        26

0.7307692307692307


/home/sara/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/sara/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/sara/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [351]:
rbf = make_pipeline(preprocessing.StandardScaler(),SVC(kernel='rbf'))
rbf.fit(X_train, y_train)

y_pred3 = rbf.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred3))
print(classification_report(y_test, y_pred3))
print(accuracy_score(y_test,y_pred3))

[[ 4  3]
 [ 0 19]]
              precision    recall  f1-score   support

           1       1.00      0.57      0.73         7
           2       0.86      1.00      0.93        19

    accuracy                           0.88        26
   macro avg       0.93      0.79      0.83        26
weighted avg       0.90      0.88      0.87        26

0.8846153846153846


In [352]:
sigmoid = make_pipeline(preprocessing.StandardScaler(),SVC(kernel='sigmoid'))
sigmoid.fit(X_train, y_train)

y_pred4 = sigmoid.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred4))
print(classification_report(y_test, y_pred4))
print(accuracy_score(y_test,y_pred4))

[[ 4  3]
 [ 1 18]]
              precision    recall  f1-score   support

           1       0.80      0.57      0.67         7
           2       0.86      0.95      0.90        19

    accuracy                           0.85        26
   macro avg       0.83      0.76      0.78        26
weighted avg       0.84      0.85      0.84        26

0.8461538461538461


<div id="bayes" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=6>
		 ج- تاثیر پارامترهای هر کرنل را بر کارآیی مدل ها تحلیل کنید.
		</br>
</div>

In [365]:
linear1 = make_pipeline(preprocessing.StandardScaler(),SVC(C=1,kernel='linear',gamma=1))
linear1.fit(X_train, y_train)

y_pred1 = linear1.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred1))
print(classification_report(y_test,y_pred1))
print(accuracy_score(y_test,y_pred1))

[[ 5  2]
 [ 1 18]]
              precision    recall  f1-score   support

           1       0.83      0.71      0.77         7
           2       0.90      0.95      0.92        19

    accuracy                           0.88        26
   macro avg       0.87      0.83      0.85        26
weighted avg       0.88      0.88      0.88        26

0.8846153846153846


In [366]:

poly = make_pipeline(preprocessing.StandardScaler(),SVC(C=10,kernel='poly', degree=1,gamma=3))
poly.fit(X_train, y_train)

y_pred2 = poly.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred2))
print(classification_report(y_test, y_pred2))
print(accuracy_score(y_test,y_pred2))

[[ 5  2]
 [ 1 18]]
              precision    recall  f1-score   support

           1       0.83      0.71      0.77         7
           2       0.90      0.95      0.92        19

    accuracy                           0.88        26
   macro avg       0.87      0.83      0.85        26
weighted avg       0.88      0.88      0.88        26

0.8846153846153846


In [367]:
rbf = make_pipeline(preprocessing.StandardScaler(),SVC(C=1,kernel='rbf',gamma=1))
rbf.fit(X_train, y_train)

y_pred3 = rbf.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred3))
print(classification_report(y_test, y_pred3))
print(accuracy_score(y_test,y_pred3))

[[ 0  7]
 [ 0 19]]
              precision    recall  f1-score   support

           1       0.00      0.00      0.00         7
           2       0.73      1.00      0.84        19

    accuracy                           0.73        26
   macro avg       0.37      0.50      0.42        26
weighted avg       0.53      0.73      0.62        26

0.7307692307692307


/home/sara/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/sara/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/sara/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [370]:
sigmoid = make_pipeline(preprocessing.StandardScaler(),SVC(C=1,kernel='sigmoid',gamma=1))
sigmoid.fit(X_train, y_train)

y_pred4 = sigmoid.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred1))
print(classification_report(y_test, y_pred1))
print(accuracy_score(y_test,y_pred1))

[[ 5  2]
 [ 1 18]]
              precision    recall  f1-score   support

           1       0.83      0.71      0.77         7
           2       0.90      0.95      0.92        19

    accuracy                           0.88        26
   macro avg       0.87      0.83      0.85        26
weighted avg       0.88      0.88      0.88        26

0.8846153846153846


<div id="bayes" style="direction:rtl;line-height:300%;">
	<font face="XB Zar" size=6>
		 د- کدام مدل عملکرد بهتری دارد؟ چرا؟
		</br>
</div>


با افزایش مقدار سی و گاما دفت کرنل پلی افزایش یافت و دقت مدل ار بی اف کاهش یافت

# 3- Student Intervention System

<div style="margin-left: 10px;font-size:25px">a) Run the code cell below to load necessary Python libraries and load the student data. Note that the last column from this dataset, 'passed', will be our target label (whether the student graduated or didn't graduate). All other columns are features about each student.</div>

In [371]:
student_data = pd.read_csv("student_data.csv")
student_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 31 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64 
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64 
 7   Fedu        395 non-null    int64 
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64 
 13  studytime   395 non-null    int64 
 14  failures    395 non-null    int64 
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher    

<div style="margin-left: 10px;font-size:25px">
  <p>  
b) Let's begin by investigating the dataset to determine how many students we have information on, and learn about the graduation rate among these students. In the code cell below, you will need to compute the following:
    </p>
    <ul>
        <li>The total number of students, n_students.</li>
        <li>The total number of features for each student, n_features.</li>
        <li>The number of those students who passed, n_passed.</li>
        <li>The number of those students who failed, n_failed.</li>
        <li>The graduation rate of the class, grad_rate, in percent (%).</li>
     </ul>

</div>

In [372]:
# TODO: Calculate number of students

n_students = student_data.shape[0]

# TODO: Calculate number of features

n_features = student_data.shape[1]

# TODO: Calculate passing students

n_passed = student_data[student_data['passed']=='yes']['passed'].count()

# TODO: Calculate failing students
n_failed = student_data[student_data['passed']=='no']['passed'].count()

# TODO: Calculate graduation rate
total=student_data['passed'].count()
grad_rate = n_passed/total

# Print the results
print("Total number of students: {}".format(n_students))
print("Number of features: {}".format(n_features))
print("Number of students who passed: {}".format(n_passed))
print("Number of students who failed: {}".format(n_failed))
print("Graduation rate of the class: {:.2f}%".format(grad_rate))

Total number of students: 395
Number of features: 31
Number of students who passed: 265
Number of students who failed: 130
Graduation rate of the class: 0.67%


<div style="margin-left: 10px;font-size:25px">
    <p>c) Preparing the Data</p>
    <p>In this section, we will prepare the data for modeling, training and testing.</p>
    <p>Identify feature and target columns
It is often the case that the data you obtain contains non-numeric features. This can be a problem, as most machine learning algorithms expect numeric data to perform computations with.

Run the code cell below to separate the student data into feature and target columns to see if any features are non-numeric.</p>
</div>




In [373]:
# Extract feature columns
feature_cols = list(student_data.columns[:-1])

# Extract target column 'passed'
target_col = student_data.columns[-1] 

# Show the list of columns
print("Feature columns:\n{}".format(feature_cols))
print("\nTarget column: {}".format(target_col))

# Separate the data into feature data and target data (X_all and y_all, respectively)
X = student_data[feature_cols]
y = student_data[target_col]

Feature columns:
['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu', 'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime', 'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc', 'Walc', 'health', 'absences']

Target column: passed


<div style="margin-left: 10px;font-size:25px">
    <p>d) Preprocess Feature Columns</p>
    <p>As you can see, there are several non-numeric columns that need to be converted! Many of them are simply yes/no, e.g. internet. These can be reasonably converted into 1/0 (binary) values.</p>
    <p>
Other columns, like Mjob and Fjob, have more than two values, and are known as categorical variables. The recommended way to handle such a column is to create as many columns as possible values (e.g. Fjob_teacher, Fjob_other, Fjob_services, etc.), and assign a 1 to one of them and 0 to all others.

These generated columns are sometimes called dummy variables, and we will use the pandas.get_dummies() function to perform this transformation. Run the code cell below to perform the preprocessing routine discussed in this section.</p>
</div>


In [374]:
def preprocess_features(X):
    ''' Preprocesses the student data and converts non-numeric binary variables into
        binary (0/1) variables. Converts categorical variables into dummy variables. '''
    
    # Initialize new output DataFrame
    output = pd.DataFrame(index = X.index)

    # Investigate each feature column for the data
    for col, col_data in X.items():

        # If data type is non-numeric, replace all binary values with 1/0
        if col_data.dtype == object and len(col_data.unique()) == 2:
            print("*****binary*****")
            print("col name: ", col, end="----")
            col_data_unique = col_data.unique()
            print("unique values: ", col_data_unique)
            col_data = col_data.replace(col_data_unique, [1, 0])

        # If data type is categorical, convert to dummy variables
        if col_data.dtype == object and len(col_data.unique()) != 2:
            print("*****categorical*****")
            print("col name: ", col, end="----")
            col_data_unique = col_data.unique()
            print("unique values: ", col_data_unique)
            # Example: 'school' => 'school_GP' and 'school_MS'
            col_data = pd.get_dummies(col_data, prefix = col)  
        
        # Collect the revised columns
        output = output.join(col_data)
    
    return output

X_preprocessed = preprocess_features(X)
X_preprocessed

*****binary*****
col name:  school----unique values:  ['GP' 'MS']
*****binary*****
col name:  sex----unique values:  ['F' 'M']
*****binary*****
col name:  address----unique values:  ['U' 'R']
*****binary*****
col name:  famsize----unique values:  ['GT3' 'LE3']
*****binary*****
col name:  Pstatus----unique values:  ['A' 'T']
*****categorical*****
col name:  Mjob----unique values:  ['at_home' 'health' 'other' 'services' 'teacher']
*****categorical*****
col name:  Fjob----unique values:  ['teacher' 'other' 'services' 'health' 'at_home']
*****categorical*****
col name:  reason----unique values:  ['course' 'other' 'home' 'reputation']
*****categorical*****
col name:  guardian----unique values:  ['mother' 'father' 'other']
*****binary*****
col name:  schoolsup----unique values:  ['yes' 'no']
*****binary*****
col name:  famsup----unique values:  ['no' 'yes']
*****binary*****
col name:  paid----unique values:  ['no' 'yes']
*****binary*****
col name:  activities----unique values:  ['no' 'yes']


school  sex  age  address  famsize  Pstatus  Medu  Fedu  Mjob_at_home  \
0         1    1   18        1        1        1     4     4             1   
1         1    1   17        1        1        0     1     1             1   
2         1    1   15        1        0        0     1     1             1   
3         1    1   15        1        1        0     4     2             0   
4         1    1   16        1        1        0     3     3             0   
..      ...  ...  ...      ...      ...      ...   ...   ...           ...   
390       0    0   20        1        0        1     2     2             0   
391       0    0   17        1        0        0     3     1             0   
392       0    0   21        0        1        0     1     1             0   
393       0    0   18        0        0        0     3     2             0   
394       0    0   19        1        0        0     1     1             0   

     Mjob_health  ...  higher  internet  romantic  famrel  freetime  goout  \
0              0  ...       1         1         1       4         3      4   
1              0  ...       1         0         1       5         3      3   
2              0  ...       1         0         1       4         3      2   
3              1  ...       1         0         0       3         2      2   
4              0  ...       1         1         1       4         3      2   
..           ...  ...     ...       ...       ...     ...       ...    ...   
390            0  ...       1         1         1       5         5      4   
391            0  ...       1         0         1       2         4      5   
392            0  ...       1         1         1       5         5      3   
393            0  ...       1         0         1       4         4      1   
394            0  ...       1         0         1       3         2      3   

     Dalc  Walc  health  absences  
0       1     1       3         6  
1       1     1       3         4  
2       2     3       3        10  
3       1     1       5         2  
4       1     2       5         4  
..    ...   ...     ...       ...  
390     4     5       4        11  
391     3     4       2         3  
392     3     3       3         3  
393     3     4       5         0  
394     3     3       5         5  

[395 rows x 43 columns]

<div style="margin-left: 10px;font-size:25px">
    <p>e) Training and Testing Data Split</p>
    <p>split the data (both features and corresponding labels) into training and test sets.(Use 300 training points (approximately 75%) and 95 testing points (approximately 25%).)</p>
</div>

In [375]:
# TODO: Import any additional functionality you may need here


from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_preprocessed, y, test_size=0.25, random_state=55)


<div style="margin-left: 10px;font-size:25px">
<p>f) In this section, you will choose 3 supervised learning models that are appropriate for this problem and available in scikit-learn. You will first discuss the reasoning behind choosing these three models by considering what you know about the data and each model's strengths and weaknesses. You will then fit the model to training data and measure the F1 score. You will need to produce three tables (one for each model) that shows the training set size, training time, prediction time, F1 score on the training set, and F1 score on the testing set.</p>
<p>The following supervised learning models are currently available in scikit-learn that you may choose from:</p>
    <ul>
        <li>Gaussian Naive Bayes (GaussianNB)</li>
        <li>K-Nearest Neighbors (KNeighbors)</li>
        <li>Stochastic Gradient Descent (SGDC)</li>
        <li>Support Vector Machines (SVM)</li>
        <li>Logistic Regression</li>
     </ul>
</div>    

In [376]:
from sklearn.naive_bayes import GaussianNB
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing
from sklearn import metrics
from sklearn.metrics import accuracy_score 
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score ,precision_score,recall_score,f1_score

## Gaussian Naive Bayes (GaussianNB)

In [377]:
gaussian = make_pipeline(preprocessing.StandardScaler(),GaussianNB())
gaussian.fit(X_train, y_train)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('gaussiannb', GaussianNB())])

In [378]:
Y_pred = gaussian.predict(X_test) 

In [379]:
accuracy_nb=round(accuracy_score(y_test,Y_pred)* 100, 2)
acc_gaussian = round(gaussian.score(X_train, y_train) * 100, 2)
from sklearn.metrics import classification_report

print(classification_report(y_test, Y_pred))
accuracy_nb=round(accuracy_score(y_test,Y_pred)* 100, 2)
acc_gaussian = round(gaussian.score(X_train, y_train) * 100, 2)

cm = confusion_matrix(y_test, Y_pred)
accuracy = accuracy_score(y_test,Y_pred)

print('Confusion matrix \n',cm)
print('accuracy_Naive Bayes: %.3f' %accuracy)


              precision    recall  f1-score   support

          no       0.69      0.30      0.42        30
         yes       0.76      0.94      0.84        69

    accuracy                           0.75        99
   macro avg       0.72      0.62      0.63        99
weighted avg       0.74      0.75      0.71        99

Confusion matrix 
 [[ 9 21]
 [ 4 65]]
accuracy_Naive Bayes: 0.747


## K-Nearest Neighbors (KNeighbors)

In [380]:
from sklearn.neighbors import KNeighborsClassifier

In [381]:
knn = make_pipeline(preprocessing.StandardScaler(),KNeighborsClassifier(n_neighbors=5))
knn.fit(X_train, y_train)
Y_pred4 = knn.predict(X_test) 

accuracy1 = accuracy_score(y_test,Y_pred4)

from sklearn.metrics import classification_report
print(classification_report(y_test, Y_pred))
accuracy_nb=round(accuracy_score(y_test,Y_pred)* 100, 2)
acc_gaussian = round(knn.score(X_train, y_train) * 100, 2)

cm1 = confusion_matrix(y_test, Y_pred)


print('Confusion matrix \n',cm1)
print('accuracy_Knn: %.3f' %accuracy1)

              precision    recall  f1-score   support

          no       0.69      0.30      0.42        30
         yes       0.76      0.94      0.84        69

    accuracy                           0.75        99
   macro avg       0.72      0.62      0.63        99
weighted avg       0.74      0.75      0.71        99

Confusion matrix 
 [[ 9 21]
 [ 4 65]]
accuracy_Knn: 0.687


## Stochastic Gradient Descent (SGDC)

In [382]:
from sklearn.linear_model import SGDClassifier 

In [390]:
sgd = make_pipeline(StandardScaler(),
                     SGDClassifier(penalty='l2', alpha=1))

sgd.fit(X_train, y_train)
Y_pred7 = sgd.predict(X_test) 

print(classification_report(y_test, Y_pred))
accuracy_nb=round(accuracy_score(y_test,Y_pred7)* 100, 2)
acc_gaussian = round(sgd.score(X_train, y_train) * 100, 2)

cm3 = confusion_matrix(y_test, Y_pred7)
accuracy2 = accuracy_score(y_test,Y_pred7)

print('Confusion matrix \n',cm3)
print('accuracy_Naive Bayes: %.3f' %accuracy2)

              precision    recall  f1-score   support

          no       0.69      0.30      0.42        30
         yes       0.76      0.94      0.84        69

    accuracy                           0.75        99
   macro avg       0.72      0.62      0.63        99
weighted avg       0.74      0.75      0.71        99

Confusion matrix 
 [[ 0 30]
 [ 0 69]]
accuracy_Naive Bayes: 0.697


## Support Vector Machines (SVM)

In [386]:
from sklearn.svm import SVC

In [389]:
svc = make_pipeline(preprocessing.StandardScaler(),SVC())
svc.fit(X_train, y_train)
Y_pred1 = svc.predict(X_test) 

from sklearn.metrics import classification_report
print('SGD Classifier_SVM')
print(classification_report(y_test, Y_pred))
accuracy_nb=round(accuracy_score(y_test,Y_pred)* 100, 2)
acc_gaussian = round(svc.score(X_train, y_train) * 100, 2)

cm2 = confusion_matrix(y_test, Y_pred)
accuracy3 = accuracy_score(y_test,Y_pred1)

print('Confusion matrix \n',cm1)
print('accuracy_SVM: %.3f' %accuracy3)

SGD Classifier_SVM
              precision    recall  f1-score   support

          no       0.69      0.30      0.42        30
         yes       0.76      0.94      0.84        69

    accuracy                           0.75        99
   macro avg       0.72      0.62      0.63        99
weighted avg       0.74      0.75      0.71        99

Confusion matrix 
 [[ 9 21]
 [ 4 65]]
accuracy_SVM: 0.707


## Logistic Regression

In [309]:
from sklearn.linear_model import LogisticRegression

In [391]:
Logistic = make_pipeline(preprocessing.StandardScaler(),LogisticRegression(multi_class='multinomial'))
Logistic.fit(X_train, y_train)

Y_pred3 = Logistic.predict(X_test) 

print('Logistic Regression')
print(classification_report(y_test, Y_pred3))
accuracy_nb=round(accuracy_score(y_test,Y_pred3)* 100, 2)
acc_gaussian = round(Logistic.score(X_train, y_train) * 100, 2)

cm = confusion_matrix(y_test, Y_pred3)
accuracy4 = accuracy_score(y_test,Y_pred)

print('Confusion matrix \n',cm)
print('accuracy_Logistic Regression: %.3f' %accuracy4)

Logistic Regression
              precision    recall  f1-score   support

          no       0.56      0.30      0.39        30
         yes       0.75      0.90      0.82        69

    accuracy                           0.72        99
   macro avg       0.65      0.60      0.60        99
weighted avg       0.69      0.72      0.69        99

Confusion matrix 
 [[ 9 21]
 [ 7 62]]
accuracy_Logistic Regression: 0.747
